development:
  adapter: postgresql
  encoding: unicode
  database: MARLONFMF_development
  pool: 5
  username: 
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: MARLONFMF_test
  pool: 5
  username: 
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: MARLONFMF_production
  pool: 5
  username: 
  password: